### ISSUE TITLE
(suggestion) More stuff in Language.txt

### ISSUE THREAD

**Issue by Blueberryy** [That1M8Head/Sonic-LockandLoad#10]
crazy that it's final and not yet all main menu options and text been added to translation file

**Comment by AeriaVelocity** [comment]
Well, that's because I'm lazy

What exactly do you need added? Or do you want me to add translations for everything or?

**Comment by Blueberryy** [comment]
Nah just options and main menu stuff would be enough if you feel like it

**Comment by AeriaVelocity** [comment]
Could you explain a bit more? I'm not totally following

**Comment by Blueberryy** [comment]
Well recent commit should do, close it for now
