### ISSUE TITLE
In Shadow's tutorial, hint for Dual Assimilator is set to talk about Chaos Spear

### ISSUE THREAD

**Issue by sierra0451** [That1M8Head/Sonic-LockandLoad#7]
Probably a wrong number set. Should be an easy fix. I did have to noclip to finish the tutorial though, not sure if there's anything else that would cause that

**Comment by AeriaVelocity** [comment]
Which part did you have to noclip at?

**Comment by sierra0451** [comment]
I had to noclip after the Dual Assimilator section. After that, the tutorial was smooth sailing to the end

**Comment by AeriaVelocity** [comment]
That fixes the issue of the hint -- didn't encounter a section where I had to noclip.

**Comment by sierra0451** [comment]
Alrighty. Thanks :)
